apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: prod
        env: env/prod
      - name: dev
        env: env/dev
  template:
    metadata:
      name: 'guestbook-{{name}}'
    spec:
      project: 'default'
      source:
        repoURL: 'https://github.com/34fathombelow/guestbook'
        targetRevision: '{{env}}'
        path: .
      destination:
        name: '{{name}}'
        namespace: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true