apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prom-stack
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
   - clusters:
      selector:
        matchLabels:
          type: 'prod'
      values:
        path: 'prod'
   - clusters:
      selector:
        matchLabels:
          type: 'dev'
      values:
        path: 'dev'
  template:
    metadata:
      name: 'kube-prometheus-stack-{{.name}}'
    spec:
      project: 'default'
      source:
        repoURL: 'https://github.com/34fathombelow/declarative_spec_demo.git'
        path: 'prometheus_addons/{{.values.path}}'
        targetRevision: HEAD
      destination:
        name: '{{.name}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
